const state={chats:[],activeChat:null,streaming:false,controller:null,config:null,theme:localStorage.getItem('fable-theme')||'system'};
window.fableState=state;
const $=id=>document.getElementById(id),chatList=$("chatList"),conversation=$("conversation"),input=$("input"),sendBtn=$("sendBtn");
const capabilityCache=new Map();
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]||c))}
function highlight(code,lang){let out=esc(code),l=(lang||'').toLowerCase();const kw={python:/\b(def|class|import|from|return|if|elif|else|for|while|in|is|and|or|not|True|False|None|try|except|with|as|async|await|yield|raise|lambda)\b/g,javascript:/\b(const|let|var|function|return|if|else|for|while|new|class|extends|import|from|export|async|await|try|catch|throw|true|false|null|undefined)\b/g,js:/\b(const|let|var|function|return|if|else|for|while|new|class|extends|import|from|export|async|await|try|catch|throw|true|false|null|undefined)\b/g,json:/("[^"\n]+")(?=\s*:)/g,css:/\b(display|position|color|background|margin|padding|width|height|flex|grid)\b/g};if(kw[l])out=out.replace(kw[l],'<span class="tok-keyword">$1</span>');return out.replace(/(&quot;.*?&quot;|&#039;.*?&#039;)/g,'<span class="tok-string">$1</span>')}
function markdown(text){const blocks=[];let source=String(text||'').replace(/\r\n/g,'\n');source=source.replace(/```([^\n]*)\n([\s\S]*?)(?:```|$)/g,(_,lang,code)=>{const id=blocks.length;blocks.push(`<div class="code-wrap"><div class="code-head"><span>${esc(lang||'code')}</span><button class="copy-code" data-code="${encodeURIComponent(code)}">Copy</button></div><pre><code>${highlight(code,lang)}</code></pre></div>`);return `\n@@CODE${id}@@\n`});source=esc(source).replace(/`([^`\n]+)`/g,'<code class="inline">$1</code>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\*([^*\n]+)\*/g,'<em>$1</em>').replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^# (.+)$/gm,'<h1>$1</h1>').replace(/^> (.+)$/gm,'<blockquote>$1</blockquote>').replace(/^(?:- |\* )(.+)$/gm,'<li>$1</li>').replace(/(<li>.*<\/li>\n?)+/g,m=>`<ul>${m}</ul>`);return source.split(/\n{2,}/).map(p=>/^<(h[1-3]|ul|blockquote|div)/.test(p.trim())?p:(p.trim()?`<p>${p.replace(/\n/g,'<br>')}</p>`:'')).join('').replace(/@@CODE(\d+)@@/g,(_,i)=>blocks[+i])}
function scrollBottom(){conversation.scrollTop=conversation.scrollHeight}
async function api(url,options={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});if(!r.ok)throw Error(await r.text());return r.json()}
function selectedModel(){return localStorage.getItem('fable-model')||state.config?.default_model||''}
function currentModel(){return state.config?.models?.find(m=>m.id===selectedModel())||null}
async function hydrateModel(slug,rerender=true){if(!slug)return null;if(capabilityCache.has(slug)){const cap=capabilityCache.get(slug);mergeCapability(cap);if(rerender)renderModels();return cap}try{const cap=await api(`/api/model/${encodeURIComponent(slug)}`);capabilityCache.set(slug,cap);mergeCapability(cap);if(rerender)renderModels();return cap}catch{return null}}
function mergeCapability(cap){const model=state.config?.models?.find(m=>m.id===cap?.id);if(model&&cap)Object.assign(model,cap)}
function renderSidebar(){const q=($('chatSearch').value||'').trim().toLowerCase();const list=state.chats.filter(c=>!q||c.title.toLowerCase().includes(q));chatList.innerHTML=list.length?list.map(c=>`<div class="chat-row ${c.id===state.activeChat?'active':''}" data-id="${c.id}"><span class="chat-title">${esc(c.title)}</span><button class="chat-menu" data-menu="${c.id}" aria-label="Chat actions">•••</button></div>`).join(''):'<div class="empty-history">No conversations found</div>'}
function renderModels(){const options=$('modelOptions'),settings=$('settingsModel');options.innerHTML=state.config.models.map(m=>`<button class="model-option ${m.id===selectedModel()?'selected':''}" data-model="${esc(m.id)}"><span>${esc(m.name)}</span><small>${esc(m.id)}</small><b>${m.reasoning?'Reasoning':''}</b></button>`).join('');settings.innerHTML=state.config.models.map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join('');settings.value=selectedModel();$('modelName').textContent=currentModel()?.name||selectedModel();updateModelControls()}
async function chooseModel(model){localStorage.setItem('fable-model',model);$('modelName').textContent=model;$('settingsModel').value=model;renderModels();closeModelPopover();await hydrateModel(model,true)}
async function loadConfig(){state.config=await api('/api/config');if(!state.config.models.length)throw Error('No models available');if(!state.config.models.some(m=>m.id===selectedModel()))localStorage.setItem('fable-model',state.config.default_model);renderModels();await hydrateModel(selectedModel(),true)}
async function loadChats(){state.chats=await api('/api/chats');renderSidebar();if(!state.activeChat&&state.chats[0])await openChat(state.chats[0].id)}
function clearConversation(){conversation.innerHTML='<div class="welcome" id="welcome"><div class="welcome-mark">✳</div><h1>How can I help?</h1><p>What would you like to explore today?</p><div class="prompt-grid"><button class="prompt-card prompt-a" data-prompt="Help me write something"><span>✎</span><strong>Help me<br/>write something</strong></button><button class="prompt-card prompt-b" data-prompt="Explain a complex topic"><span>♧</span><strong>Explain a<br/>complex topic</strong></button><button class="prompt-card prompt-c" data-prompt="Summarize this for me"><span>▤</span><strong>Summarize<br/>this for me</strong></button><button class="prompt-card prompt-d" data-prompt="Help with coding"><span>&lt;/&gt;</span><strong>Help with<br/>coding</strong></button></div></div>';wirePrompts()}
async function openChat(id){const d=await api(`/api/chats/${id}`);state.activeChat=id;renderSidebar();conversation.innerHTML='';d.messages.forEach(m=>appendMessage(m.role,m.content,m.reasoning_summary));if(!d.messages.length)clearConversation();localStorage.setItem('fable-model',d.chat.model);renderModels();await hydrateModel(d.chat.model,true);closeSidebar();scrollBottom()}
function wireCopy(root){root.querySelectorAll('.copy-code').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(decodeURIComponent(b.dataset.code));b.textContent='Copied';setTimeout(()=>b.textContent='Copy',1200)}catch{b.textContent='Copy'}})}
function reasoningMarkup(summary){if(!summary)return '';return `<details class="reasoning-box"><summary><span class="reasoning-dot">✦</span><span>Reasoning summary</span><span class="reasoning-hint">provider summary</span></summary><div class="reasoning-text">${markdown(summary)}</div></details>`}
function appendMessage(role,content,reasoningSummary=''){const w=document.createElement('div');w.className=`message ${role}`;w.innerHTML=role==='user'?`<div class="bubble">${esc(content)}</div>`:`<div class="assistant-content">${reasoningMarkup(reasoningSummary)}<div class="answer-body">${markdown(content)}</div></div>`;conversation.appendChild(w);wireCopy(w);return w}
function addStreamingMessage(){const w=document.createElement('div');w.className='message assistant';const model=currentModel();const effort=model?.reasoning?getReasoning(model):null;const reasoningPanel=model?.reasoning?`<details class="reasoning-box" open><summary><span class="reasoning-dot">✦</span><span>Reasoning</span><span class="reasoning-hint">${esc(effort||'active')}</span></summary><div class="reasoning-text"><span class="reasoning-live">Thinking…</span><div class="reasoning-disclaimer">Only the model's provider-supplied summary is shown here.</div></div></details>`:'';w.innerHTML=`<div class="assistant-content">${reasoningPanel}<span class="typing"><i></i><i></i><i></i></span><div class="answer-body"></div></div>`;conversation.appendChild(w);return w}
function setStreaming(on){state.streaming=on;sendBtn.innerHTML=on?'<span class="stop-icon">■</span>':'<span>↑</span>';sendBtn.setAttribute('aria-label',on?'Stop generating':'Send')}
async function sendMessage(e){e?.preventDefault();if(state.streaming){state.controller?.abort();return}const text=input.value.trim();if(!text)return;if(!state.activeChat){const c=await api('/api/chats',{method:'POST',body:JSON.stringify({model:selectedModel()})});state.activeChat=c.id;state.chats.unshift(c);renderSidebar()}$('welcome')?.remove();appendMessage('user',text);input.value='';resizeInput();updateCount();scrollBottom();const assistant=addStreamingMessage(),contentEl=assistant.querySelector('.answer-body');let answer='';let reasoning='';const model=currentModel();const effort=model?.reasoning?getReasoning(model):null;setStreaming(true);state.controller=new AbortController();try{const body={content:text,model:selectedModel(),max_tokens:getMaxTokens(model),system_prompt:localStorage.getItem('fable-system-prompt')??state.config.default_system_prompt};if(effort)body.reasoning_effort=effort;const r=await fetch(`/api/chats/${state.activeChat}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},signal:state.controller.signal,body:JSON.stringify(body)});if(!r.ok||!r.body)throw Error(await r.text());const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const events=buffer.split('\n\n');buffer=events.pop()||'';for(const event of events){const line=event.split('\n').find(x=>x.startsWith('data: '));if(!line)continue;const d=JSON.parse(line.slice(6));if(d.type==='reasoning_summary'){reasoning+=d.text;renderStreamingReasoning(assistant,reasoning);scrollBottom()}if(d.type==='token'){answer+=d.text;contentEl.innerHTML=markdown(answer);wireCopy(assistant);scrollBottom()}if(d.type==='done'&&d.reasoning_summary&&!reasoning){reasoning=d.reasoning_summary;renderStreamingReasoning(assistant,reasoning)}if(d.type==='error')throw Error(d.message)}}if(!answer)contentEl.innerHTML='<p class="stopped">Generation stopped.</p>';await loadChats()}catch(err){if(err.name!=='AbortError')contentEl.innerHTML=`<p class="error">Error: ${esc(err.message)}</p>`;else if(!answer)contentEl.innerHTML='<p class="stopped">Generation stopped.</p>'}finally{setStreaming(false);state.controller=null;scrollBottom()}}
function renderStreamingReasoning(assistant,summary){let box=assistant.querySelector('.reasoning-box');if(!box){const content=assistant.querySelector('.assistant-content');box=document.createElement('details');box.className='reasoning-box';box.open=true;box.innerHTML='<summary><span class="reasoning-dot">✦</span><span>Reasoning summary</span><span class="reasoning-hint">live</span></summary><div class="reasoning-text"></div>';content.prepend(box)}const text=box.querySelector('.reasoning-text');text.innerHTML=markdown(summary)+`<div class="reasoning-disclaimer">Provider-supplied summary only; private chain-of-thought is not exposed.</div>`;wireCopy(box)}
function getMaxTokens(model){const cap=Math.max(256,Number(model?.max_output)||Number(state.config?.default_max_tokens)||4096);let n=Number(localStorage.getItem('fable-max-tokens'));if(!Number.isFinite(n)||n<256)n=Math.min(4096,cap);return Math.min(Math.round(n),cap)}
function getReasoning(model){if(!model?.reasoning)return null;const levels=model.reasoning_levels||[];const v=localStorage.getItem(`fable-reasoning-${model.id}`)||model.reasoning_default||levels[0];return levels.includes(v)?v:null}
function updateModelControls(){const model=currentModel();if(!model)return;const cap=Math.max(256,Number(model.max_output)||Number(state.config?.default_max_tokens)||32768);const max=getMaxTokens(model);$('maxTokens').value=max;$('maxTokens').max=cap;$('tokenRange').max=cap;$('tokenRange').value=max;$('tokenRange').step=cap>=10000?256:1;$('tokenValue').value=max;$('tokenLimitLabel').textContent=`up to ${formatTokens(cap)}`;$('tokenScaleMax').textContent=formatTokens(cap);$('responseHelp').textContent=`Set maximum output tokens for ${model.name}`;const rs=$('reasoningSetting');if(model.reasoning&&model.reasoning_levels?.length){rs.classList.remove('hidden');const grid=$('effortGrid');const selected=getReasoning(model);grid.innerHTML=model.reasoning_levels.map(level=>`<button class="effort-btn ${level===selected?'active':''}" data-effort="${esc(level)}">${esc(level[0].toUpperCase()+level.slice(1))}</button>`).join('')}else{rs.classList.add('hidden');$('effortGrid').innerHTML=''}}
function formatTokens(n){return n>=100000?`${Math.round(n/1000)}K`:n>=1000?`${Math.round(n/1000)}K`:String(n)}
function resizeInput(){input.style.height='auto';input.style.height=Math.min(input.scrollHeight,180)+'px'}function updateCount(){const n=input.value.length;$('charCount').textContent=`${n} / 200000`}
async function createNewChat(){if(state.streaming)return;const c=await api('/api/chats',{method:'POST',body:JSON.stringify({model:selectedModel()})});state.chats.unshift(c);state.activeChat=c.id;renderSidebar();clearConversation();closeSidebar()}
let pendingDelete=null;function confirmDelete(id){pendingDelete=id;$('modalBackdrop').classList.remove('hidden')}function closeModal(){pendingDelete=null;$('modalBackdrop').classList.add('hidden')}async function deleteChat(){if(!pendingDelete)return;const id=pendingDelete;closeModal();await api(`/api/chats/${id}`,{method:'DELETE'});if(state.activeChat===id){state.activeChat=null;clearConversation()}await loadChats()}
async function renameChat(id){const c=state.chats.find(x=>x.id===id);if(!c)return;const t=prompt('Rename chat',c.title);if(t===null)return;await api(`/api/chats/${id}`,{method:'PATCH',body:JSON.stringify({title:t})});await loadChats()}
chatList.addEventListener('click',async e=>{const m=e.target.closest('[data-menu]');if(m){e.stopPropagation();const id=m.dataset.menu;const a=prompt('Type rename or delete');if(a?.toLowerCase()==='rename')await renameChat(id);else if(a?.toLowerCase()==='delete')confirmDelete(id);return}const row=e.target.closest('.chat-row');if(row)await openChat(row.dataset.id)});
function wirePrompts(){conversation.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{input.value=b.dataset.prompt;resizeInput();updateCount();input.focus()})}
function openSidebar(){document.body.classList.add('drawer-open');$('sidebar').classList.add('open');$('drawerBackdrop').classList.add('show')}function closeSidebar(){document.body.classList.remove('drawer-open');$('sidebar').classList.remove('open');$('drawerBackdrop').classList.remove('show')}
function openModelPopover(){const r=$('modelSwitch').getBoundingClientRect();$('modelPopover').style.top=`${r.bottom+8}px`;$('modelPopover').style.left=`${Math.max(12,r.left)}px`;$('modelPopover').classList.toggle('hidden');renderModels()}function closeModelPopover(){$('modelPopover').classList.add('hidden')}
$('newChatBtn').onclick=createNewChat;$('composer').onsubmit=sendMessage;input.addEventListener('input',()=>{resizeInput();updateCount()});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();resizeInput()}});$('openSidebar').onclick=openSidebar;$('closeSidebar').onclick=closeSidebar;$('drawerBackdrop').onclick=closeSidebar;$('chatSearch').addEventListener('input',renderSidebar);$('modelSwitch').onclick=openModelPopover;$('modelOptions').addEventListener('click',async e=>{const b=e.target.closest('[data-model]');if(b)await chooseModel(b.dataset.model)});document.addEventListener('click',e=>{if(!e.target.closest('#modelSwitch')&&!e.target.closest('#modelPopover'))closeModelPopover()});$('settingsModel').addEventListener('change',e=>chooseModel(e.target.value));$('modalCancel').onclick=closeModal;$('modalConfirm').onclick=deleteChat;$('modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};$('effortGrid').addEventListener('click',e=>{const b=e.target.closest('[data-effort]');const m=currentModel();if(b&&m){localStorage.setItem(`fable-reasoning-${m.id}`,b.dataset.effort);updateModelControls()}});
function applyTheme(theme){state.theme=theme;localStorage.setItem('fable-theme',theme);const dark=theme==='dark'||(theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.classList.toggle('dark',dark);document.querySelectorAll('[data-theme]').forEach(b=>b.classList.toggle('active',b.dataset.theme===theme));$('topTheme').textContent=dark?'☼':'☾'}function toggleTheme(){applyTheme(document.documentElement.classList.contains('dark')?'light':'dark')}$('topTheme').onclick=toggleTheme;window.matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if(state.theme==='system')applyTheme('system')});
function openSettings(){updateModelControls();$('maxTokens').value=getMaxTokens(currentModel());$('tokenValue').value=$('maxTokens').value;$('systemPrompt').value=localStorage.getItem('fable-system-prompt')??state.config.default_system_prompt;$('settingsModel').value=selectedModel();$('settingsBackdrop').classList.remove('hidden')}function closeSettings(){$('settingsBackdrop').classList.add('hidden')}$('settingsBtn').onclick=openSettings;$('settingsClose').onclick=closeSettings;$('settingsBackdrop').onclick=e=>{if(e.target.id==='settingsBackdrop')closeSettings()};$('maxTokens').addEventListener('input',e=>{$('tokenValue').value=e.target.value;$('tokenRange').value=e.target.value});$('tokenRange').addEventListener('input',e=>{$('maxTokens').value=e.target.value;$('tokenValue').value=e.target.value});$('resetPrompt').onclick=()=>{$('systemPrompt').value=state.config.default_system_prompt};$('saveSettings').onclick=()=>{const m=currentModel();const cap=Math.max(256,Number(m?.max_output)||Number(state.config?.default_max_tokens)||4096);const n=Math.min(Math.max(256,Number($('maxTokens').value)||4096),cap);localStorage.setItem('fable-max-tokens',n);localStorage.setItem('fable-system-prompt',$('systemPrompt').value);localStorage.setItem('fable-model',$('settingsModel').value);renderModels();closeSettings()};document.querySelectorAll('[data-collapse]').forEach(b=>b.onclick=()=>{const target=$(b.dataset.collapse);target.classList.toggle('collapsed');b.querySelector('.collapse-icon').textContent=target.classList.contains('collapsed')?'⌄':'⌃'});document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>applyTheme(b.dataset.theme));
let deferredInstall=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});$('installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null}else alert('Use your browser menu and choose “Install app” or “Add to Home Screen”.')};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js'));applyTheme(state.theme);(async()=>{try{await loadConfig();await loadChats();wirePrompts();updateCount()}catch(e){conversation.innerHTML=`<div class="welcome"><h1>Fable failed to start</h1><p>${esc(e.message)}</p></div>`}})();