const state={chats:[],activeChat:null,streaming:false,controller:null,config:null,theme:localStorage.getItem('fable-theme')||'system'};
window.fableState=state;
const $=id=>document.getElementById(id),chatList=$('chatList'),conversation=$('conversation'),input=$('input'),sendBtn=$('sendBtn');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]||c));
const api=async(url,options={})=>{const r=await fetch(url,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});if(!r.ok)throw Error(await r.text());return r.json()};
const selectedModel=()=>localStorage.getItem('fable-model')||state.config?.default_model||'';
const currentModel=()=>state.config?.models?.find(m=>m.id===selectedModel())||null;
const formatTokens=n=>n>=100000?`${Math.round(n/1000)}K`:n>=1000?`${Math.round(n/1000)}K`:String(n);
function markdown(text){const blocks=[];let source=String(text||'').replace(/\r\n/g,'\n');source=source.replace(/```([^\n]*)\n([\s\S]*?)(?:```|$)/g,(_,lang,code)=>{const id=blocks.length,label=(lang||'text').trim()||'text';blocks.push(`<div class="code-wrap"><div class="code-head"><span>${esc(label)}</span><button class="copy-code" data-code="${encodeURIComponent(code)}">Copy</button></div><pre><code>${window.highlight?window.highlight(code,label):esc(code)}</code></pre></div>`);return `\n@@CODE${id}@@\n`});source=esc(source).replace(/`([^`\n]+)`/g,'<code class="inline">$1</code>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\*([^*\n]+)\*/g,'<em>$1</em>').replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^# (.+)$/gm,'<h1>$1</h1>').replace(/^> (.+)$/gm,'<blockquote>$1</blockquote>').replace(/^(?:- |\* )(.+)$/gm,'<li>$1</li>').replace(/(<li>.*<\/li>\n?)+/g,m=>`<ul>${m}</ul>`);return source.split(/\n{2,}/).map(p=>/^<(h[1-3]|ul|blockquote|div)/.test(p.trim())?p:(p.trim()?`<p>${p.replace(/\n/g,'<br>')}</p>`:'')).join('').replace(/@@CODE(\d+)@@/g,(_,i)=>blocks[+i])}
function wireCopy(root){root.querySelectorAll('.copy-code').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(decodeURIComponent(b.dataset.code));b.textContent='Copied';setTimeout(()=>b.textContent='Copy',1200)}catch{b.textContent='Copy'}})}
function renderSidebar(){const q=($('chatSearch')?.value||'').trim().toLowerCase();const list=state.chats.filter(c=>!q||String(c.title||'').toLowerCase().includes(q));chatList.innerHTML=list.length?list.map(c=>`<div class="chat-row ${c.id===state.activeChat?'active':''}" data-id="${esc(c.id)}"><span class="chat-title">${esc(c.title||'New chat')}</span><button class="chat-menu" data-menu="${esc(c.id)}" aria-label="Chat actions" title="Chat actions">•••</button></div>`).join(''):'<div class="empty-history">No conversations found</div>'}
function renderModels(){if(!state.config?.models)return;const options=$('modelOptions'),settings=$('settingsModel');options.innerHTML=state.config.models.map(m=>`<button class="model-option ${m.id===selectedModel()?'selected':''}" data-model="${esc(m.id)}"><span>${esc(m.name||m.id)}</span><small>${esc(m.id)}</small></button>`).join('');settings.innerHTML=state.config.models.map(m=>`<option value="${esc(m.id)}">${esc(m.name||m.id)}</option>`).join('');settings.value=selectedModel();$('modelName').textContent=currentModel()?.name||selectedModel();updateModelControls()}
async function hydrateModel(slug){if(!slug)return;try{const cap=await api(`/api/model/${encodeURIComponent(slug)}`);const m=state.config?.models?.find(x=>x.id===slug);if(m)Object.assign(m,cap);updateModelControls()}catch{}}
async function loadConfig(){state.config=await api('/api/config');if(!state.config.models?.length)throw Error('No models available');if(!state.config.models.some(m=>m.id===selectedModel()))localStorage.setItem('fable-model',state.config.default_model);renderModels();await hydrateModel(selectedModel())}
async function loadChats(){state.chats=await api('/api/chats');renderSidebar();if(!state.activeChat&&state.chats[0])await openChat(state.chats[0].id)}
function clearConversation(){conversation.innerHTML='<div class="welcome" id="welcome"><div class="welcome-mark">✳</div><h1>How can I help?</h1><p>What would you like to explore today?</p><div class="prompt-grid"><button class="prompt-card prompt-a" data-prompt="Help me write something"><span>✎</span><strong>Help me<br/>write something</strong></button><button class="prompt-card prompt-b" data-prompt="Explain a complex topic"><span>♧</span><strong>Explain a<br/>complex topic</strong></button><button class="prompt-card prompt-c" data-prompt="Summarize this for me"><span>▤</span><strong>Summarize<br/>this for me</strong></button><button class="prompt-card prompt-d" data-prompt="Help with coding"><span>&lt;/&gt;</span><strong>Help with<br/>coding</strong></button></div></div>';wirePrompts()}
function appendMessage(role,content){const w=document.createElement('div');w.className=`message ${role}`;w.innerHTML=role==='user'?`<div class="bubble">${esc(content)}</div>`:`<div class="assistant-content"><div class="answer-body">${markdown(content)}</div></div>`;conversation.appendChild(w);wireCopy(w);return w}
async function openChat(id){const d=await api(`/api/chats/${id}`);state.activeChat=id;localStorage.setItem('fable-model',d.chat.model);conversation.innerHTML='';if(d.messages?.length)d.messages.forEach(m=>appendMessage(m.role,m.content));else clearConversation();renderSidebar();renderModels();await hydrateModel(d.chat.model);closeSidebar();window.fableForceScroll?.()}
function addStreamingMessage(){const w=document.createElement('div');w.className='message assistant';w.innerHTML='<div class="assistant-content"><span class="typing"><i></i><i></i><i></i></span><div class="answer-body"></div></div>';conversation.appendChild(w);return w}
function setStreaming(on){state.streaming=on;sendBtn.innerHTML=on?'<span class="stop-icon" aria-hidden="true"></span>':'<span class="send-glyph" aria-hidden="true"></span>';sendBtn.classList.toggle('is-stop',on);sendBtn.setAttribute('aria-label',on?'Stop generating':'Send');sendBtn.title=on?'Stop generating':'Send'}
function getMaxTokens(model){const cap=Math.max(256,Number(model?.max_output)||Number(state.config?.default_max_tokens)||4096);let n=Number(localStorage.getItem('fable-max-tokens'));if(!Number.isFinite(n)||n<256)n=Math.min(4096,cap);return Math.min(Math.round(n),cap)}
async function sendMessage(e){e?.preventDefault();if(state.streaming){state.controller?.abort();return}const text=input.value.trim();if(!text)return;if(!state.activeChat){const c=await api('/api/chats',{method:'POST',body:JSON.stringify({model:selectedModel()})});state.activeChat=c.id;state.chats.unshift(c);renderSidebar()}$('welcome')?.remove();appendMessage('user',text);input.value='';resizeInput();updateCount();window.fableForceScroll?.();const assistant=addStreamingMessage(),contentEl=assistant.querySelector('.answer-body'),typing=assistant.querySelector('.typing');let answer='';setStreaming(true);state.controller=new AbortController();try{const body={content:text,model:selectedModel(),max_tokens:getMaxTokens(currentModel()),system_prompt:localStorage.getItem('fable-system-prompt')??state.config.default_system_prompt};const r=await fetch(`/api/chats/${state.activeChat}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},signal:state.controller.signal,body:JSON.stringify(body)});if(!r.ok||!r.body)throw Error(await r.text());const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const events=buffer.split('\n\n');buffer=events.pop()||'';for(const event of events){const line=event.split('\n').find(x=>x.startsWith('data: '));if(!line)continue;let d;try{d=JSON.parse(line.slice(6))}catch{continue}if(d.type==='token'){if(typing)typing.remove();answer+=d.text||'';contentEl.innerHTML=markdown(answer);wireCopy(assistant);window.fableForceScroll?.()}if(d.type==='done'&&d.content&&!answer){answer=d.content;contentEl.innerHTML=markdown(answer);wireCopy(assistant)}if(d.type==='error')throw Error(d.message||'Generation failed')}}}if(!answer)contentEl.innerHTML='<p class="stopped">Generation stopped.</p>';await loadChats()}catch(err){if(err.name!=='AbortError')contentEl.innerHTML=`<p class="error">Error: ${esc(err.message||'Request failed')}</p>`;else if(!answer)contentEl.innerHTML='<p class="stopped">Generation stopped.</p>'}finally{setStreaming(false);state.controller=null;window.fableForceScroll?.()}}
function updateModelControls(){const model=currentModel();if(!model)return;const cap=Math.max(256,Number(model.max_output)||Number(state.config?.default_max_tokens)||32768);const max=getMaxTokens(model),n=$('maxTokens'),r=$('tokenRange'),v=$('tokenValue');if(n){n.value=max;n.max=cap}if(r){r.max=cap;r.value=max;r.step=cap>=10000?256:1}if(v)v.value=max;if($('tokenLimitLabel'))$('tokenLimitLabel').textContent=`up to ${formatTokens(cap)}`;if($('tokenScaleMax'))$('tokenScaleMax').textContent=formatTokens(cap);if($('responseHelp'))$('responseHelp').textContent=`Set maximum output tokens for ${model.name||model.id}`}
function resizeInput(){input.style.height='auto';input.style.height=Math.min(input.scrollHeight,180)+'px'}function updateCount(){const n=input.value.length;$('charCount').textContent=`${n} / 200000`}
async function createNewChat(){if(state.streaming)return;const c=await api('/api/chats',{method:'POST',body:JSON.stringify({model:selectedModel()})});state.chats.unshift(c);state.activeChat=c.id;renderSidebar();clearConversation();closeSidebar();window.fableForceScroll?.()}
let pendingDelete=null;function closeModal(){pendingDelete=null;$('modalBackdrop').classList.add('hidden')}async function deleteChat(){if(!pendingDelete)return;const id=pendingDelete,btn=$('modalConfirm');btn.disabled=true;btn.textContent='Deleting…';try{await api(`/api/chats/${id}`,{method:'DELETE'});if(state.activeChat===id){state.activeChat=null;conversation.innerHTML='';clearConversation()}state.chats=state.chats.filter(x=>x.id!==id);renderSidebar()}catch(e){alert(e.message||'Delete failed')}finally{btn.disabled=false;btn.textContent='Delete';closeModal()}}
function confirmDelete(id){pendingDelete=id;const c=state.chats.find(x=>x.id===id);$('modalBackdrop').classList.remove('hidden');$('modalBackdrop').querySelector('h2').textContent='Delete conversation?';$('modalBackdrop').querySelector('p').textContent=`“${c?.title||'This conversation'}” will be permanently deleted. This action cannot be undone.`;$('modalConfirm').focus()}
async function renameChat(id){const c=state.chats.find(x=>x.id===id);if(!c)return;let box=$('renameDialog');if(!box){box=document.createElement('div');box.id='renameDialog';box.className='modal-backdrop hidden';box.innerHTML='<div class="modal rename-modal" role="dialog" aria-modal="true"><div class="modal-eyebrow">Conversation</div><h2>Rename chat</h2><p>Give this conversation a clear name.</p><label class="rename-field"><span>Chat name</span><input id="renameInput" maxlength="100" autocomplete="off"/></label><div class="modal-actions"><button class="modal-cancel" id="renameCancel">Cancel</button><button class="modal-primary" id="renameConfirm">Save name</button></div></div></div>';document.body.appendChild(box);$('renameCancel').onclick=()=>box.classList.add('hidden');$('renameConfirm').onclick=saveRename;$('renameInput').onkeydown=e=>{if(e.key==='Enter')saveRename();if(e.key==='Escape')box.classList.add('hidden')}}box.dataset.id=id;$('renameInput').value=c.title||'';box.classList.remove('hidden');requestAnimationFrame(()=>$('renameInput').focus())}
async function saveRename(){const box=$('renameDialog'),id=box?.dataset.id,name=$('renameInput')?.value.trim();if(!id||!name)return;const btn=$('renameConfirm');btn.disabled=true;btn.textContent='Saving…';try{await api(`/api/chats/${id}`,{method:'PATCH',body:JSON.stringify({title:name})});const c=state.chats.find(x=>x.id===id);if(c)c.title=name;renderSidebar();box.classList.add('hidden')}catch(e){alert(e.message||'Rename failed')}finally{btn.disabled=false;btn.textContent='Save name'}}
let actionMenu=null;function closeActionMenu(){actionMenu?.remove();actionMenu=null}function openActionMenu(anchor,id){closeActionMenu();const menu=document.createElement('div');menu.className='chat-action-menu';menu.innerHTML='<button data-action="rename"><span>✎</span>Rename</button><button data-action="delete" class="danger"><span>⌫</span>Delete</button>';document.body.appendChild(menu);const r=anchor.getBoundingClientRect();menu.style.top=`${Math.min(innerHeight-100,r.bottom+4)}px`;menu.style.left=`${Math.min(innerWidth-180,Math.max(8,r.right-170))}px`;menu.querySelector('[data-action="rename"]').onclick=()=>{closeActionMenu();renameChat(id)};menu.querySelector('[data-action="delete"]').onclick=()=>{closeActionMenu();confirmDelete(id)};actionMenu=menu}
chatList.addEventListener('click',async e=>{const m=e.target.closest('[data-menu]');if(m){e.stopPropagation();openActionMenu(m,m.dataset.menu);return}const row=e.target.closest('.chat-row');if(row)await openChat(row.dataset.id)});document.addEventListener('click',e=>{if(actionMenu&&!e.target.closest('.chat-action-menu')&&!e.target.closest('.chat-menu'))closeActionMenu()});
function wirePrompts(){conversation.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{input.value=b.dataset.prompt;resizeInput();updateCount();input.focus()})}
function openSidebar(){document.body.classList.add('drawer-open');$('sidebar').classList.add('open');$('drawerBackdrop').classList.add('show')}function closeSidebar(){document.body.classList.remove('drawer-open');$('sidebar').classList.remove('open');$('drawerBackdrop').classList.remove('show')}
function openModelPopover(){const r=$('modelSwitch').getBoundingClientRect();$('modelPopover').style.top=`${r.bottom+8}px`;$('modelPopover').style.left=`${Math.max(12,r.left)}px`;$('modelPopover').classList.remove('hidden');renderModels()}function closeModelPopover(){$('modelPopover').classList.add('hidden')}
async function chooseModel(model){if(state.streaming)return;localStorage.setItem('fable-model',model);renderModels();closeModelPopover();await hydrateModel(model)}
function applyTheme(theme){state.theme=theme;localStorage.setItem('fable-theme',theme);const dark=theme==='dark'||(theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.classList.toggle('dark',dark);document.querySelectorAll('[data-theme]').forEach(b=>b.classList.toggle('active',b.dataset.theme===theme));$('topTheme').textContent=dark?'☼':'☾'}
function openSettings(){updateModelControls();$('systemPrompt').value=localStorage.getItem('fable-system-prompt')??state.config.default_system_prompt;$('settingsModel').value=selectedModel();$('settingsBackdrop').classList.remove('hidden')}
function closeSettings(){$('settingsBackdrop').classList.add('hidden')}
$('newChatBtn').onclick=createNewChat;$('composer').onsubmit=sendMessage;input.addEventListener('input',()=>{resizeInput();updateCount()});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage(e)}});$('openSidebar').onclick=openSidebar;$('closeSidebar').onclick=closeSidebar;$('drawerBackdrop').onclick=closeSidebar;$('chatSearch').addEventListener('input',renderSidebar);$('modelSwitch').onclick=openModelPopover;$('modelOptions').addEventListener('click',async e=>{const b=e.target.closest('[data-model]');if(b)await chooseModel(b.dataset.model)});document.addEventListener('click',e=>{if(!e.target.closest('#modelSwitch')&&!e.target.closest('#modelPopover'))closeModelPopover()});$('settingsModel').addEventListener('change',e=>chooseModel(e.target.value));$('modalCancel').onclick=closeModal;$('modalConfirm').onclick=deleteChat;$('modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};$('topTheme').onclick=()=>applyTheme(document.documentElement.classList.contains('dark')?'light':'dark');$('maxTokens').addEventListener('input',e=>{$('tokenValue').value=e.target.value;$('tokenRange').value=e.target.value});$('tokenRange').addEventListener('input',e=>{$('maxTokens').value=e.target.value;$('tokenValue').value=e.target.value});$('resetPrompt').onclick=()=>{$('systemPrompt').value=state.config.default_system_prompt};$('saveSettings').onclick=()=>{const m=currentModel(),cap=Math.max(256,Number(m?.max_output)||Number(state.config?.default_max_tokens)||4096),n=Math.min(Math.max(256,Number($('maxTokens').value)||4096),cap);localStorage.setItem('fable-max-tokens',n);localStorage.setItem('fable-system-prompt',$('systemPrompt').value);localStorage.setItem('fable-model',$('settingsModel').value);renderModels();closeSettings()};document.querySelectorAll('[data-collapse]').forEach(b=>b.onclick=()=>{const target=$(b.dataset.collapse);if(!target)return;target.classList.toggle('collapsed');const icon=b.querySelector('.collapse-icon');if(icon)icon.textContent=target.classList.contains('collapsed')?'⌄':'⌃'});document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>applyTheme(b.dataset.theme));
let deferredInstall=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});$('installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null}else alert('Use your browser menu and choose “Install app” or “Add to Home Screen”.')};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js'));applyTheme(state.theme);(async()=>{try{await loadConfig();await loadChats();wirePrompts();updateCount()}catch(e){conversation.innerHTML=`<div class="welcome"><h1>Fable failed to start</h1><p>${esc(e.message||'Unknown error')}</p></div>`}})();