const state={chats:[],activeChat:null,streaming:false,controller:null,config:null,streamAnswer:''};
const $=id=>document.getElementById(id),chatList=$("chatList"),conversation=$("conversation"),input=$("input"),sendBtn=$("sendBtn");
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function highlight(code,lang){let out=esc(code),l=(lang||'').toLowerCase();const kw={python:/\b(def|class|import|from|return|if|elif|else|for|while|in|is|and|or|not|True|False|None|try|except|with|as|async|await|yield|raise|lambda)\b/g,javascript:/\b(const|let|var|function|return|if|else|for|while|new|class|extends|import|from|export|async|await|try|catch|throw|true|false|null|undefined)\b/g,js:/\b(const|let|var|function|return|if|else|for|while|new|class|extends|import|from|export|async|await|try|catch|throw|true|false|null|undefined)\b/g,json:/(&quot;[^&]+?&quot;)(?=\s*:)/g,css:/\b(display|position|color|background|margin|padding|width|height|flex|grid)\b/g};if(kw[l])out=out.replace(kw[l],'<span class="tok-keyword">$1</span>');return out.replace(/(&quot;.*?&quot;|&#039;.*?&#039;)/g,'<span class="tok-string">$1</span>')}
function markdown(text){const blocks=[];let source=String(text||'').replace(/\r\n/g,'\n');source=source.replace(/```([^\n]*)\n([\s\S]*?)(?:```|$)/g,(_,lang,code)=>{const id=blocks.length;blocks.push(`<div class="code-wrap"><div class="code-head"><span>${esc(lang||'code')}</span><button class="copy-code" data-code="${encodeURIComponent(code)}">Copy</button></div><pre><code>${highlight(code,lang)}</code></pre></div>`);return `\n@@CODE${id}@@\n`});source=esc(source).replace(/`([^`\n]+)`/g,'<code class="inline">$1</code>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\*([^*\n]+)\*/g,'<em>$1</em>').replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^# (.+)$/gm,'<h1>$1</h1>').replace(/^> (.+)$/gm,'<blockquote>$1</blockquote>').replace(/^(?:- |\* )(.+)$/gm,'<li>$1</li>').replace(/(<li>.*<\/li>\n?)+/g,m=>`<ul>${m}</ul>`);source=source.split(/\n{2,}/).map(p=>/^<(h[1-3]|ul|blockquote|div)/.test(p.trim())?p:(p.trim()?`<p>${p.replace(/\n/g,'<br>')}</p>`:'')).join('').replace(/@@CODE(\d+)@@/g,(_,i)=>blocks[+i]);return source}
function scrollBottom(){conversation.scrollTop=conversation.scrollHeight}
async function api(url,options={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});if(!r.ok)throw Error(await r.text());return r.json()}
function renderSidebar(){chatList.innerHTML=state.chats.length?state.chats.map(c=>`<div class="chat-row ${c.id===state.activeChat?'active':''}" data-id="${c.id}"><span class="chat-title">${esc(c.title)}</span><button class="chat-menu" data-menu="${c.id}">•••</button></div>`).join(''):'<div class="empty-history">No chats yet</div>'}
async function loadConfig(){state.config=await api('/api/config');$('modelSelect')?.remove();$('modelLabel').textContent=state.config.default_model}
async function loadChats(){state.chats=await api('/api/chats');renderSidebar();if(!state.activeChat&&state.chats[0])await openChat(state.chats[0].id)}
function clearConversation(){conversation.innerHTML='<div class="welcome" id="welcome"><div class="welcome-mark">F</div><h1>How can I help?</h1><p>Ask anything. Your chats are saved in this browser.</p></div>'}
async function openChat(id){const d=await api(`/api/chats/${id}`);state.activeChat=id;renderSidebar();conversation.innerHTML='';d.messages.forEach(m=>appendMessage(m.role,m.content));if(!d.messages.length)clearConversation();$('modelLabel').textContent=d.chat.model;$('sidebar').classList.remove('open');scrollBottom()}
function wireCopy(root){root.querySelectorAll('.copy-code').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(decodeURIComponent(b.dataset.code));b.textContent='Copied';setTimeout(()=>b.textContent='Copy',1200)})}
function appendMessage(role,content){const w=document.createElement('div');w.className=`message ${role}`;w.innerHTML=role==='user'?`<div class="bubble">${esc(content)}</div>`:`<div class="assistant-content">${markdown(content)}</div>`;conversation.appendChild(w);wireCopy(w);return w}
function addStreamingMessage(){const w=document.createElement('div');w.className='message assistant';w.innerHTML='<div class="assistant-content"><span class="typing"><i></i><i></i><i></i></span></div>';conversation.appendChild(w);return w}
function setStreaming(on){state.streaming=on;sendBtn.innerHTML=on?'<span class="stop-icon">■</span>':'<span>↑</span>';sendBtn.setAttribute('aria-label',on?'Stop generating':'Send')}
async function sendMessage(e){e?.preventDefault();if(state.streaming){state.controller?.abort();return}const text=input.value.trim();if(!text)return;if(!state.activeChat){const c=await api('/api/chats',{method:'POST',body:JSON.stringify({model:state.config.default_model})});state.activeChat=c.id;state.chats.unshift(c);renderSidebar()}$('welcome')?.remove();appendMessage('user',text);input.value='';resizeInput();scrollBottom();const assistant=addStreamingMessage(),contentEl=assistant.querySelector('.assistant-content');let answer='';setStreaming(true);state.controller=new AbortController();try{const r=await fetch(`/api/chats/${state.activeChat}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},signal:state.controller.signal,body:JSON.stringify({content:text,model:$('modelLabel').textContent,max_tokens:Number(localStorage.getItem('fable-max-tokens')||state.config.default_max_tokens),system_prompt:localStorage.getItem('fable-system-prompt')||state.config.default_system_prompt})});if(!r.ok||!r.body)throw Error(await r.text());const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const events=buffer.split('\n\n');buffer=events.pop()||'';for(const event of events){const line=event.split('\n').find(x=>x.startsWith('data: '));if(!line)continue;const d=JSON.parse(line.slice(6));if(d.type==='token'){answer+=d.text;contentEl.innerHTML=markdown(answer);wireCopy(assistant);scrollBottom()}if(d.type==='error')throw Error(d.message)}}if(!answer)contentEl.innerHTML='<p class="stopped">Generation stopped.</p>';await loadChats()}catch(err){if(err.name!=='AbortError')contentEl.innerHTML=`<p class="error">Error: ${esc(err.message)}</p>`;else if(!answer)contentEl.innerHTML='<p class="stopped">Generation stopped.</p>'}finally{setStreaming(false);state.controller=null;scrollBottom()}}
function resizeInput(){input.style.height='auto';input.style.height=Math.min(input.scrollHeight,180)+'px'}
async function createNewChat(){if(state.streaming)return;const c=await api('/api/chats',{method:'POST',body:JSON.stringify({model:state.config.default_model})});state.chats.unshift(c);state.activeChat=c.id;renderSidebar();clearConversation()}
let pendingDelete=null;function confirmDelete(id){pendingDelete=id;$('modalBackdrop').classList.remove('hidden')}function closeModal(){pendingDelete=null;$('modalBackdrop').classList.add('hidden')}
async function deleteChat(){if(!pendingDelete)return;const id=pendingDelete;closeModal();await api(`/api/chats/${id}`,{method:'DELETE'});if(state.activeChat===id){state.activeChat=null;clearConversation()}await loadChats()}
async function renameChat(id){const c=state.chats.find(x=>x.id===id);if(!c)return;const t=prompt('Rename chat',c.title);if(t===null)return;await api(`/api/chats/${id}`,{method:'PATCH',body:JSON.stringify({title:t})});await loadChats()}
chatList.addEventListener('click',async e=>{const m=e.target.closest('[data-menu]');if(m){e.stopPropagation();const id=m.dataset.menu;const a=prompt('Type rename or delete');if(a?.toLowerCase()==='rename')await renameChat(id);else if(a?.toLowerCase()==='delete')confirmDelete(id);return}const row=e.target.closest('.chat-row');if(row)await openChat(row.dataset.id)});
$('newChatBtn').onclick=createNewChat;$('composer').onsubmit=sendMessage;input.addEventListener('input',resizeInput);input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();resizeInput()}});$('openSidebar').onclick=()=>$('sidebar').classList.add('open');$('closeSidebar').onclick=()=>$('sidebar').classList.remove('open');$('modalCancel').onclick=closeModal;$('modalConfirm').onclick=deleteChat;$('modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};
function setTheme(dark){document.documentElement.classList.toggle('dark',dark);localStorage.setItem('fable-theme',dark?'dark':'light');$('themeIcon').textContent=dark?'☀':'☾';$('themeText').textContent=dark?'Light mode':'Dark mode';$('topTheme').textContent=dark?'☀':'☾'}function toggleTheme(){setTheme(!document.documentElement.classList.contains('dark'))}$('themeBtn').onclick=toggleTheme;$('topTheme').onclick=toggleTheme;
function openSettings(){ $('maxTokens').value=localStorage.getItem('fable-max-tokens')||state.config.default_max_tokens;$('systemPrompt').value=localStorage.getItem('fable-system-prompt')||state.config.default_system_prompt;$('settingsBackdrop').classList.remove('hidden') }$('settingsBtn').onclick=openSettings;$('settingsClose').onclick=()=>$('settingsBackdrop').classList.add('hidden');$('saveSettings').onclick=()=>{localStorage.setItem('fable-max-tokens',Math.max(1,Math.min(200000,Number($('maxTokens').value)||state.config.default_max_tokens)));localStorage.setItem('fable-system-prompt',$('systemPrompt').value);$('settingsBackdrop').classList.add('hidden')};$('modelSwitch').onclick=()=>alert('Models are loaded from the API. Current model: '+$('modelLabel').textContent);
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js'));setTheme(localStorage.getItem('fable-theme')==='dark');(async()=>{try{await loadConfig();await loadChats()}catch(e){conversation.innerHTML=`<div class="welcome"><h1>Fable failed to start</h1><p>${esc(e.message)}</p></div>`}})();
